[project.illumos]
github = "illumos/illumos-gate"

[project.omnios-build]
github = "oxidecomputer/helios-omnios-build"
use_ssh = true
site_sh = true

[project.omnios-extra]
github = "oxidecomputer/helios-omnios-extra"
use_ssh = true
site_sh = true
