[project.illumos]
github = "illumos/illumos-gate"

[project.omnios-build]
github = "omniosorg/omnios-build"
use_ssh = false
site_sh = true

[project.omnios-extra]
github = "omniosorg/omnios-extra"
use_ssh = false
site_sh = true
